-- ============================================================
-- V1: Esquema baseline (estado real de la BD)
-- Generado a partir del esquema que Hibernate creaba con ddl-auto.
-- A partir de aquí, TODOS los cambios de esquema deben ser
-- nuevas migraciones (V2, V3, ...) — nunca editar esta.
-- ============================================================

CREATE TABLE usuarios (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre             VARCHAR(255) NOT NULL,
    email              VARCHAR(255) NOT NULL,
    contrasena         VARCHAR(255) NOT NULL,
    dni                VARCHAR(255),
    telefono           VARCHAR(255),
    rol                VARCHAR(255) CHECK (rol IN ('USER', 'LIBRARIAN', 'ADMIN')),
    estado             VARCHAR(255) CHECK (estado IN ('ACTIVO', 'BLOQUEADO')),
    reset_token        VARCHAR(255),
    reset_token_expiry TIMESTAMP,
    CONSTRAINT uk_usuarios_email UNIQUE (email),
    CONSTRAINT uk_usuarios_dni UNIQUE (dni)
);

CREATE TABLE libros (
    isbn               VARCHAR(255) PRIMARY KEY,
    titulo             VARCHAR(255) NOT NULL,
    autor              VARCHAR(255) NOT NULL,
    categoria          VARCHAR(255),
    año_pub            INTEGER CHECK (año_pub >= 1900),
    editorial          VARCHAR(255),
    copias_disponibles INTEGER DEFAULT 1,
    estado             VARCHAR(255) CHECK (estado IN ('DISPONIBLE', 'PRESTADO', 'RESERVADO', 'PERDIDO'))
);

CREATE TABLE prestamos (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id         BIGINT,
    libro_isbn         VARCHAR(255),
    fecha_prestamo     DATE,
    fecha_devolucion   DATE,
    fecha_entrega_real DATE,
    estado             VARCHAR(255) CHECK (estado IN ('ACTIVO', 'DEVUELTO', 'ATRASADO')),
    CONSTRAINT fk_prestamos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios (id),
    CONSTRAINT fk_prestamos_libro   FOREIGN KEY (libro_isbn) REFERENCES libros (isbn)
);

CREATE TABLE multas (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prestamo_id BIGINT,
    monto       DECIMAL(10, 2),
    estado      VARCHAR(255) CHECK (estado IN ('PENDIENTE', 'PAGADO')),
    CONSTRAINT fk_multas_prestamo FOREIGN KEY (prestamo_id) REFERENCES prestamos (id)
);
